creation_rules:
  - path_regex: secrets/.*\.sops$
    key_groups:
    - age:
      - age1eggdzmjp2h4a68kn0j5zay72s7s6tc7qzak6cy9zp3dj0rwxxetsmz4t52 # from ~/.config/sops/age/keys.txt
      - age1xraazexzkzx4840mky23rzaxjghdp0fdh5h3dhfawpqz92snjcxq5l7ldv # from ssh-to-age
