# markdownlint (CLI) configuration
default: true

# Line wrapping aligned with STYLE.md guidance (~100 columns)
MD013:
  line_length: 100
  heading_line_length: 0
  code_block_line_length: 0
  tables: false

# Require fence-style code blocks for consistency
MD046:
  style: fenced

# Only flag duplicate headings at the same nesting level
MD024:
  siblings_only: true
