zstyle :plugin:fast-syntax-highlighting theme "neg"
typeset -g FAST_THEME_NAME="neg"
: ${FAST_HIGHLIGHT_STYLES[negdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[negunknown-token]:=none}
: ${FAST_HIGHLIGHT_STYLES[negreserved-word]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negalias]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negsuffix-alias]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negbuiltin]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negfunction]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negcommand]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negprecommand]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negcommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[neghashed-command]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negpath]:=none}
: ${FAST_HIGHLIGHT_STYLES[negpath_pathseparator]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negglobbing]:=fg=114}
: ${FAST_HIGHLIGHT_STYLES[negglobbing-ext]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[neghistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[negsingle-hyphen-option]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negdouble-hyphen-option]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[negsingle-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negdouble-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negdollar-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negback-or-dollar-double-quoted-argument]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negback-dollar-quoted-argument]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[negredirection]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[negcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[negvariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[negmathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[negmathnum]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[negmatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[negassign-array-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-operator]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[negexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[neghere-string-tri]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[neghere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[neghere-string-var]:=fg=177,bg=19}
: ${FAST_HIGHLIGHT_STYLES[negsecondary]:=zdharma}
: ${FAST_HIGHLIGHT_STYLES[negcase-input]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negcase-parentheses]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[negcase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[negcorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[negincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[negsubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[negsubtle-bg]:=bg=17}
: ${FAST_HIGHLIGHT_STYLES[negpath-to-dir]:=fg=248,underline}
: ${FAST_HIGHLIGHT_STYLES[negpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[negbracket-level-1]:=fg=117}
: ${FAST_HIGHLIGHT_STYLES[negbracket-level-2]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[negbracket-level-3]:=fg=90}
: ${FAST_HIGHLIGHT_STYLES[negglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[negsubcommand]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negsingle-sq-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negdouble-sq-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negdouble-paren]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negoptarg-string]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negoptarg-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[negrecursive-base]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-stackdump]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-swift]:=fg=219,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-temp]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-toml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-prql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-textile]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ipynb]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vala]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fmp12]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ai]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-urlview]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-am]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-colors]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-stderr]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wiki]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-class]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-au]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-part]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tfnt]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-klwp]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-asciidoc]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-C]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-F]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-H]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-plist]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-M]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-json5]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-alac]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-R]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mp4a]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-S]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-br]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-scpt]:=fg=219,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-Z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vimp]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-a]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-c]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-e]:=fg=245,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-msmtprc]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cc]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-f]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mp4v]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-target]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-h]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cl]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-o]:=fg=236,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sparseimage]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-r]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-s]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cp]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-t]:=fg=28,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cr]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-v]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cs]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-z]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fb2]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jsonc]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zcompdump]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sample]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-aac]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cab]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-db]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jsonl]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ppts]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-opus]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-error]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-caf]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-feature]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pptx]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bak]:=fg=247,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jad]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rasi]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dl]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-svelte]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dylib]:=fg=241}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-car]:=fg=57}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bat]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-kak]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ear]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dat]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pak]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-map]:=fg=248,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-par]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pas]:=fg=73,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pbxproj]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rar]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sar]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tar]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-war]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gba]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sav]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-toast]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gbc]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-agda]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-libsonnet]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wav]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-taz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bbl]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vapi]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-el]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-yaml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cbr]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vba]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sass]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-scss]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ex]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pbm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cbz]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xcworkspacedata]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-md5]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xbm]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ace]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sbt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fonts]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vbs]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-icc]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bck]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-incomplete]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tbz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tcsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pptsm]:=fg=31,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fcm]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-icm]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pcf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-PDF]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tcc]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ico]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vcd]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vcf]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ics]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pcm]:=fg=34,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xcf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-scm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tcl]:=fg=34,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cda]:=fg=34,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gb]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gitattributes]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pcx]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-adf]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-3g2]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bdf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gg]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cdi]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-snapshot]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-profile]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-8eu]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mdb]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gl]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-odb]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ldf]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mde]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-flac]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-aiff]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-go]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mdf]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rmvb]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cdr]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gs]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pdf]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rdf]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-frag]:=fg=142}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vdf]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-odm]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vert]:=fg=142}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xspf]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vdi]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-docm]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-odp]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nds]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ods]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-odt]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gitignore]:=fg=240}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mdx]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-astro]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-deb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-warc]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-WARC]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-docx]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hh]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-patch]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xcconfig]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hi]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tdy]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-PFA]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gel]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gem]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lagda]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hs]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-3ga]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sed]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zshenv]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-reg]:=fg=33,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-IFO]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pem]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nes]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-net]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-key]:=fg=74,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-3gp]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bfe]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cfg]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-htoprc]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dff]:=fg=36,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tex]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ii]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-afm]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-in]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pfa]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pfb]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tfstate]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ffp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wgsl]:=fg=97}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vfd]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nfo]:=fg=248,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pfm]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-containerignore]:=fg=240}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tfm]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-attheme]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zipx]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-example]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-accdb]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sfv]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pages]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-accde]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-egg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zlogin]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-Xmodmap]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cgm]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-oga]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-diff]:=bg=7,fg=16,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ggl]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dockerignore]:=fg=240}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fehbg]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tga]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-js]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-accdr]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ogg]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-latex]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-accdt]:=fg=161}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-state]:=fg=1,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ogm]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pgm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xlsm]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pgn]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pgp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ogv]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-torrent]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ogx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xlsx]:=fg=14,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sqlite]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ahk]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tgz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lha]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-agdai]:=fg=34}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-chm]:=fg=15,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pptxm]:=fg=31,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-entitlements]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-muttrc]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m4]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vhd]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tbz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xltm]:=fg=14,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lhs]:=fg=34,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-php]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mht]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bib]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xltx]:=fg=14,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-added]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ZIP]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-Xresources]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cache]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gif]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nib]:=fg=57}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bin]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mid]:=fg=37,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-numbers]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pid]:=fg=1,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hin]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sid]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-n3]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tif]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sig]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-markdown]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-git]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nim]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lit]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zig]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cpio]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vil]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vim]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pk3]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nix]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-md]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zip]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hgignore]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mf]:=fg=110,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mysql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mk]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-viminfo]:=fg=56}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ml]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cljc]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-indd]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cjs]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ejs]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-djv]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zstd]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mjs]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cljs]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cljw]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nc]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-CFUserTextEncoding]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mka]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mkd]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pkg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nt]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xkb]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fm2]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-coffee]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mkv]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rkt]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-elc]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-blg]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-flc]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-clj]:=fg=64,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mustache]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fli]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dll]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-alp]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-old]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-eln]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-flif]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-github]:=fg=36}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xla]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jpeg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-alz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mobi]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-flv]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-info]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tdesktop]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pls]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sls]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pc]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cmd]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ply]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xls]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-adoc]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-emf]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dmg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tlz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-PL]:=fg=73,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pl]:=fg=73}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pm]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-img]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-eml]:=fg=90,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bmp]:=fg=110,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-amr]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dmp]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ps]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wma]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-py]:=fg=30,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-qml]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-comp]:=fg=142}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tmp]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-yml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sms]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-enc]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-snippets]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-localized]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wmv]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xcuserstate]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pacnew]:=fg=33,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ini]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fnl]:=fg=64,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xinitrc]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mng]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rnc]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-midi]:=fg=37,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pcap]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-png]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lnk]:=fg=39}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-qt]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-conf]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rng]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-VOB]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-anx]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fnt]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gp3]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gp4]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fp7]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mp2]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mp3]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mp4]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-MOV]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ra]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rb]:=fg=33,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rc]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dump]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-doc]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-com]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rm]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mod]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-JPG]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-Xauthority]:=fg=4,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-timer]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-log]:=fg=238,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-DS_Store]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pod]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fon]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-scala]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rs]:=fg=73,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ru]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dot]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vob]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-for]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mpeg]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-F03]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sha1]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rom]:=fg=222,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-F08]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-deny]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mov]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mjpeg]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sc]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ape]:=fg=34,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zoo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bpg]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ipa]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-epf]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-apk]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gpg]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mpc]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jpg]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-a00]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-so]:=fg=22,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cpp]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mpg]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ipk]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-CR2]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-st]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hpp]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-eps]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-f03]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sx]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ppm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jidgo]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-f08]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rpm]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-spl]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xpi]:=fg=74,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vpk]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pps]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ppt]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xpm]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tfvars]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fxml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-spv]:=fg=136}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tf]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tg]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-spx]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tk]:=fg=34,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-scan]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ts]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-socket]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-aria2]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-p12]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-arc]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bash_logout]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-erb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-swap]:=fg=95}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-irb]:=fg=33,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-arj]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mdump]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-erl]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nrg]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-org]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-err]:=fg=160,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ISO]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-icls]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-crx]:=fg=74,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-drw]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-chrt]:=fg=14,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zlogout]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wrl]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-html]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-asc]:=fg=74,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vb]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lrz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-srt]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-82p]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-asf]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-st5]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dsf]:=fg=36,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-32x]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-csh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gsf]:=fg=61}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-asm]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bsp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lesshst]:=fg=248,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ksh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-psd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-msg]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ass]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ssa]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-msi]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-css]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-psf]:=fg=2,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jsm]:=fg=245}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dart]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-iso]:=fg=134,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-csv]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jsp]:=fg=245}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xsd]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xsh]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-S3M]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jnlp]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jsx]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zsh]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rss]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rst]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-eps2]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-83p]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-eps3]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dtd]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tsv]:=fg=28}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tsx]:=fg=74,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dash]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zst]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-btm]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gemspec]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-modulemap]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-woff2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dhall]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ctp]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-atr]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ftn]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-htm]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-otf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nth]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dts]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-icns]:=fg=25,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wv]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ttf]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-etx]:=fg=246}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-stl]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ttl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m2v]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dfont]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sassc]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cue]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vtt]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sty]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-AVI]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lua]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pub]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-a52]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sub]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-A64]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pug]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-aux]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-epsf]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sug]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vcard]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vue]:=fg=250,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-orig]:=fg=241,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-epsi]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-theme]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-s3m]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dotm]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m3u]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-out]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sup]:=fg=116,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nuv]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fvd]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-avi]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jsonnet]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m4a]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dvi]:=fg=249,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m4b]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-yuv]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-storyboard]:=fg=196}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-fish]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-webm]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-a64]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-webp]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-svg]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-wvc]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-f4v]:=fg=75,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m4r]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lzma]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-j64]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-8xe]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m4v]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-json]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-desktop]:=fg=75}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-8xp]:=fg=204}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-udeb]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dwg]:=fg=216}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-awk]:=fg=103}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hgrc]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-TIFF]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tiff]:=fg=33}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-epub]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bash_history]:=fg=103,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-a78]:=fg=222}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-service]:=fg=81}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-glsl]:=fg=70,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vmdk]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zx]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-signature]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-owl]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xwd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zwc]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-swo]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-djvu]:=fg=249}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-swp]:=fg=247,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vhdx]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-axa]:=fg=37,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-divx]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-netrc]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-localstorage]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-exe]:=fg=111}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rlib]:=fg=236,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-svgz]:=fg=25}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-dicom]:=fg=110}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pxd]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rdata]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-RData]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-automount]:=fg=66}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-archimate]:=fg=57}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jxl]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bz2]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-axv]:=fg=13,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-F90]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-cxx]:=fg=24,bold,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-F95]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pxm]:=fg=24,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bash_login]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hxx]:=fg=247}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-typelib]:=fg=99}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-gnumeric]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lz4]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zpaq]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-txt]:=fg=248}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-txz]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pgsql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-xcsettings]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-pyc]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-qcow2]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-f90]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-mfasl]:=fg=244,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-f95]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-SKIP]:=fg=235}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-moon]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-p7s]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-http]:=fg=90,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-hjson]:=fg=29,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-rake]:=fg=60}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-s7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-t7z]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lzh]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-device]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-woff]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tmTheme]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ttytterrc]:=fg=5,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lzo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-tzo]:=fg=61,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-jhtm]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-msql]:=fg=83}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-allow]:=fg=24}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-vimrc]:=fg=56,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-prisma]:=fg=33,underline}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m3u8]:=fg=28,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-nimble]:=fg=64}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-less]:=fg=31}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-lisp]:=fg=74}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-java]:=fg=245,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ovpn]:=fg=33,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-m2ts]:=fg=75,bold}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-zprofile]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-ndjson]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-bash_profile]:=fg=103,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-sgml]:=fg=29}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-norg]:=fg=249,italic}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-qcow]:=fg=89}
: ${FAST_HIGHLIGHT_STYLES[negfile-extensions-webloc]:=fg=5,bold}
# 🥟 pie
