{
  imports = [
    ./boot.nix
    ./environment.nix
    ./filesystems.nix
    ./kernel/params.nix
    ./kernel/sysctl.nix
    ./kernel/patches-amd.nix
    ./profiles/security.nix
    ./profiles/performance.nix
    ./profiles/aliases.nix
    ./net
    ./oomd.nix
    ./irqbalance.nix
    ./zram.nix
    ./pkgs.nix
    ./systemd
    ./users.nix
    ./virt.nix
  ];
}
