{
  imports = [
    ./systemd
    ./net
    ./profiles/security.nix
    ./profiles/performance.nix
    ./profiles/debug.nix
    ./profiles/work.nix
    ./profiles/vm.nix
    ./profiles/aliases.nix
    ./kernel
    ./boot
    ./virt
    ./oomd.nix
    ./nix-ld.nix
    ./pkgs.nix
    ./random.nix
    ./time.nix
  ];
}
