#!/usr/bin/env zsh
# abstract: remove current album from disk (moves to ~/trash/music/) after confirmation
# Usage: mpd_del_album [ARTIST]
#   If ARTIST not provided, uses current artist from mpc. Asks confirmation and
#   moves the album directory under $base to ~/trash/music/.
# Source: http://devel.japh.se/mpd_del_album/
# 2012-05-10 18:11:36

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  print "Usage: $(basename "$0") [ARTIST]"
  print "Remove current album (as detected by mpc) by moving its directory to ~/trash/music/."
  exit 0
fi

IFS="$(printf '\n\t')"
mpd_del_album_artist="$@"

[ -z $mpd_del_album_artist ] \
  && mpd_del_album_artist=$(mpc --format '%artist%' | head -1)

export mpd_del_album_artist
base=/one/music
album="$(mpc --format '%file%'|head -1 | perl -pe 's{(.+)/.+$}{$1}')"

printf "Remove:\n \e[38;5;30m$album\e[m ? [y/N] "
read answer;

if [[ $answer != 'y' ]]; then
    warn 'bailing out'
else
    mv -v "$base/$album" ~/trash/music/
fi

unset -v mpd_del_album_artist

